#!/bin/sh /etc/rc.common
# Copyright (c) 2026 OpenWrt.org

START=50

USE_PROCD=1
PROG=/sbin/mstpd
UBUS_PROG=/usr/bin/ucode
UBUS_WRAP=/usr/libexec/mstpd-ubus.uc

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -d -s
	procd_set_param respawn
	procd_close_instance

	procd_open_instance ubus
	procd_set_param command "$UBUS_PROG" "$UBUS_WRAP"
	procd_set_param respawn
	procd_close_instance
}
